/** Regular short hangout talk. House wallets use this more than tape slang. */

export const TALK_THING = [
  "this chat", "this room", "this hour", "today", "tonight", "this morning", "last night", "monday",
  "the weekend", "my phone", "the wifi", "my battery", "sleep", "food", "coffee", "work",
  "this weather", "my brain", "my eyes", "this hoodie", "the fridge", "my alarm", "this chair", "my back",
  "the gym", "that song", "this show", "the dog", "my roommate", "the sun", "this tab", "the clock",
  "this week", "nobody", "everybody", "y'all", "this playlist", "my neck", "this blanket", "the kitchen",
  "that nap", "my lunch", "this break", "my tabs", "this notification", "that text", "my calendar", "this meeting",
  "this city", "my window", "this water", "the sidewalk", "my shoes", "this queue", "that laugh",
] as const;

export const TALK_STATE = [
  "is so slow", "is so loud", "is so quiet", "is a joke", "is fine", "is winning", "is mid", "is elite",
  "is not it", "is doing too much", "is on one", "is back", "is gone", "feels late", "feels early", "is random",
  "is the same", "is different today", "is so real", "is killing me", "is saving me", "can wait", "can't wait", "is the vibe",
  "is no vibe", "won't stop", "already ended", "just started", "is overdue", "is late as usual", "needs a minute", "hit different",
  "is cooked", "still loading", "is calling", "is ignoring me", "is a whole mood", "is a problem", "is not a problem", "is unbeatable",
  "is so boring", "is so good", "got me again", "is wild today", "is peaceful", "is messy", "is clean actually", "is too much",
  "is not enough", "is hitting", "is missing", "is underrated", "is overrated", "is carrying me", "is stalling",
] as const;

export const TALK_END = [
  "", " tbh", " fr", " ngl", " tho", " idk", " lol", " lmao",
  " for real", " rn", " today", " tonight", " again", " as usual", " still", " somehow",
  " i swear", " no cap",
] as const;

export const TALK_LINE = [
  "you eat yet",
  "you good",
  "you still up",
  "i'm starving",
  "coffee first",
  "water first",
  "need food",
  "can't sleep",
  "one more then i sleep",
  "go sleep",
  "who is even awake",
  "night crew",
  "early crew",
  "i'm back",
  "was afk",
  "brb",
  "phone died",
  "wifi died",
  "battery at 4%",
  "what did i miss",
  "nothing much",
  "same as always",
  "quiet in here",
  "then it got loud",
  "y'all wild",
  "this chat",
  "i love this room",
  "y'all are a mess",
  "good morning to some of you",
  "i felt that",
  "mood",
  "real",
  "same",
  "same here",
  "i needed that",
  "that was random",
  "anyway",
  "wait i lost the plot",
  "explain",
  "i'm listening",
  "tell me",
  "no way",
  "for real?",
  "who said that",
  "that's you",
  "not me",
  "always you",
  "i was just thinking that",
  "great minds",
  "or tired minds",
  "both",
  "fair",
  "ok then",
  "alright bet",
  "i'll be back",
  "don't wait up",
  "missed that",
  "scroll back",
  "you still here",
  "you working",
  "you on break",
  "long day",
  "short day somehow",
  "monday already",
  "weekend loading",
  "weekend gone already",
  "this weather",
  "too hot",
  "too cold",
  "perfect out actually",
  "i'm in bed",
  "should be in bed",
  "eyes hurt",
  "neck hurt",
  "need a walk",
  "need a stretch",
  "gym later maybe",
  "gym skipped",
  "that's on me",
  "that's on you",
  "we in the same boat",
  "or just me",
  "not just you",
  "i see you",
  "i hear you",
  "say less",
  "say more",
  "wait what",
  "huh",
  "what",
  "ok ok",
  "hmm",
  "maybe",
  "doubt",
  "possible",
  "you're funny",
  "stop",
  "nah you right",
  "you right",
  "i hate that you're right",
  "ok continue",
  "missed me?",
  "didn't miss me",
  "i'm here",
  "still here",
  "barely here",
  "half asleep",
  "fully awake unfortunately",
  "that nap was elite",
  "that nap was a scam",
  "alarm won",
  "alarm lost",
  "snooze won",
  "coffee hasn't hit",
  "coffee hit too hard",
  "i need a snack",
  "fridge is empty",
  "fridge is judging me",
  "what's for dinner",
  "what's for lunch",
  "i forgot to eat",
  "i ate twice already",
  "hydrate",
  "touch grass maybe",
  "later",
  "soon",
  "not soon",
  "give me a minute",
  "give me ten",
  "i'm on it",
  "i'm not on it",
  "brain lag",
  "brain offline",
  "brain back",
  "tabs are a crime",
  "too many tabs",
  "phone too bright",
  "room too dark",
  "music on",
  "music off",
  "what you watching",
  "what you listening to",
  "send the song",
  "that song is stuck",
  "show is mid",
  "show is actually good",
  "i paused it",
  "i binged too much",
  "roommate is loud",
  "house is quiet",
  "dog wants out",
  "cat on the keyboard",
  "someone texted",
  "i'm not answering that",
  "i'll answer later",
  "notifications off",
  "notifications on again",
  "calendar is mean",
  "meeting in 10",
  "meeting cancelled thank god",
  "work can wait",
  "work cannot wait",
  "on lunch",
  "off lunch",
  "back from a walk",
  "legs tired",
  "eyes tired",
  "soul tired",
  "it's fine",
  "it's not fine but it's fine",
  "we move",
  "we sit",
  "we snack",
  "we hydrate",
  "we survive monday",
  "we made it to friday",
  "is it friday",
  "it is not friday",
  "close enough",
  "not close enough",
  "i blinked and it's night",
  "sun's still up?",
  "when did it get late",
  "when did it get early",
  "good luck today",
  "good luck tonight",
  "you got this",
  "we got this",
  "maybe we got this",
  "rest",
  "eat",
  "drink water",
  "unclench",
  "shoulders down",
  "breathe",
  "ok i breathed",
  "that helped a little",
  "that didn't help",
  "trying again",
  "i'm out for a bit",
  "back in a bit",
  "don't do anything wild",
  "too late y'all did",
  "classic",
  "anyway food",
  "anyway sleep",
  "anyway water",
  "who wants coffee",
  "who wants food",
  "who is sleeping",
  "who is working",
  "raise your hand if tired",
  "that's all of us",
  "respectfully i'm done",
  "respectfully i'm in",
  "this is the hangout now",
  "tape can wait",
  "charts can wait",
  "human hours",
  "snack hours",
  "sleep hours",
  "i'm just talking",
  "we can just talk",
  "that's allowed",
  "needed this",
  "this room is home",
  "y'all keep me sane",
  "y'all keep me insane",
  "both can be true",
  "ok i'm done talking",
  "ok one more",
  "ok actually one more",
  "that's the last one",
  "liar i'll be back",
] as const;

export const TALK_ASK = [
  "you eat yet",
  "you good",
  "you still up",
  "you working",
  "you on break",
  "you back",
  "what did i miss",
  "you hungry",
  "coffee?",
  "water?",
  "you going out",
  "you staying in",
  "how was that",
  "you serious",
  "wait what",
  "you saw that",
  "who is awake",
  "anyone else tired",
  "you free later",
  "what's the move tonight",
  "you coming back",
  "you still here",
  "how long you been up",
  "you ate",
  "you drinking water",
  "you stretching",
  "you good tho",
  "why you up",
  "go sleep?",
  "one more?",
  "you busy",
  "weekend plans",
  "monday hit you too",
  "you feel that",
  "same?",
  "you too?",
  "or just me",
  "what you watching",
  "what you listening to",
  "you in bed",
  "you still working",
  "you off yet",
  "how was lunch",
  "how was the walk",
  "you good after that",
  "who cooked",
  "who slept",
  "anyone else hungry",
  "anyone else done",
  "we hanging or what",
  "y'all good",
  "who needs coffee",
  "who needs a nap",
  "what time is it even",
  "is it late there",
  "is it early there",
  "you around",
  "you free",
  "talk to me",
  "what's up",
  "how you been",
  "you been ok",
  "rough day?",
  "good day?",
  "you surviving",
  "we surviving?",
  "snack check",
  "sleep check",
  "water check",
  "mood check",
  "you laughing at what",
  "what happened",
  "who started this",
  "why is it always us",
  "you coming back later",
  "save me a seat",
  "you still in the room",
  "don't leave yet",
  "one more chat?",
  "you heard me",
  "you there",
  "hello?",
  "yo you good",
  "hey you eat",
  "hey you sleep",
] as const;

export const TALK_BACK = [
  "same", "real", "mood", "facts", "i felt that", "not me", "that's you", "always you",
  "fair", "true", "wait what", "say more", "i'm listening", "tell me", "no way", "for real",
  "who said that", "that's crazy", "i needed that", "same here", "i was just thinking that", "great minds", "or tired minds", "both",
  "ok then", "alright", "bet", "i'll be back", "don't wait up", "missed that", "scroll back", "nothing much",
  "same as always", "quiet in here", "then it got loud", "y'all wild", "this chat", "i love this room", "y'all are a mess", "who is even awake",
  "go sleep", "one more then i sleep", "can't sleep", "hungry", "that was random", "anyway", "wait i lost the plot", "explain",
  "i'm with you", "not with you", "stop", "you're funny", "nah you right", "ok ok", "hmm", "maybe",
  "doubt", "possible", "i see you", "we in the same boat", "coffee first", "water first", "i'm afk", "was afk",
  "phone died", "wifi died", "i'm back", "ok continue", "what", "huh", "lol ok", "lmao ok",
  "that's allowed", "needed this", "tape can wait", "charts can wait", "human hours", "snack hours", "sleep hours", "we can just talk",
  "i hear you", "i see it", "not just you", "or just you", "that's on me", "that's on you", "close enough", "not close enough",
  "good luck", "you got this", "we got this", "rest", "eat", "hydrate", "breathe", "unclench",
  "i'm here", "still here", "barely here", "half asleep", "fully awake unfortunately", "alarm won", "snooze won", "coffee hasn't hit",
  "i need a snack", "fridge is empty", "what's for dinner", "i forgot to eat", "later", "soon", "give me a minute", "brain lag",
  "too many tabs", "music on", "send the song", "show is mid", "i paused it", "roommate is loud", "house is quiet", "i'm not answering that",
  "work can wait", "on lunch", "back from a walk", "it's fine", "we move", "we snack", "is it friday", "it is not friday",
  "when did it get late", "good luck today", "ok i breathed", "trying again", "i'm out for a bit", "back in a bit", "anyway food", "anyway sleep",
  "who wants coffee", "that's all of us", "this is the hangout now", "y'all keep me sane", "ok one more", "liar i'll be back", "how you been", "you been ok",
] as const;

export const TALK_BACK_END = [
  "", " lol", " lmao", " tho", " fr", " ngl", " tbh", " idk",
  " rn", " for real", " i swear", " no cap", " too", " same",
] as const;

export const TALK_GREET = [
  "gm", "gm gm", "morning", "hey", "yo", "what's good", "we here", "back",
  "hey hey", "yo yo", "gm chat", "hey chat", "yo room", "morning crew", "night crew", "i'm here",
  "we in", "still here", "gm everyone", "hey y'all", "what's up", "how you been", "you good", "made it",
  "another day", "we made it", "gm fr", "hey again", "back again", "look who it is", "the usuals", "early gang",
  "late gang", "hello", "hi", "sup", "you around", "room's open",
] as const;

const HANGOUT_RE =
  /\b(sleep|slept|food|eat|ate|coffee|hungry|starv|tired|wifi|phone|battery|weekend|monday|friday|weather|gym|work|alarm|hoodie|fridge|dog|song|show|afk|brb|nap|snack|water|hydrate|walk|lunch|dinner|bed|awake|tired|chat|room|mood|real|same here|you good|how you been|what's up|hangout|human hours|tabs|music|roommate)\b/;

export function isHangoutText(text: string | undefined): boolean {
  const s = (text || "").toLowerCase();
  if (!s) return false;
  if (/\b(reclaim|wick|tape|bid|ask|fade|liquidity|invalidation|stop run|higher low)\b/.test(s)) return false;
  return HANGOUT_RE.test(s) || /^(gm|gn|yo|hey|hi|sup|morning|what's up|you good|you eat|you still)\b/.test(s.trim());
}

export function hangoutCardinality(): number {
  return (
    TALK_THING.length * TALK_STATE.length * TALK_END.length +
    TALK_LINE.length +
    TALK_ASK.length +
    TALK_GREET.length +
    TALK_BACK.length * TALK_BACK_END.length
  );
}

function pick<T>(arr: readonly T[], rng: () => number): T {
  return arr[Math.floor(rng() * arr.length)]!;
}

export function hangoutCombo(rng: () => number): string {
  return `${pick(TALK_THING, rng)} ${pick(TALK_STATE, rng)}${pick(TALK_END, rng)}`.replace(/\s+/g, " ").trim();
}

export function hangoutSay(rng: () => number): string {
  const roll = rng();
  if (roll < 0.28) return pick(TALK_LINE, rng);
  if (roll < 0.4) return pick(TALK_ASK, rng);
  if (roll < 0.5) return pick(TALK_GREET, rng);
  return hangoutCombo(rng);
}

export function hangoutReply(rng: () => number, last = ""): string {
  const s = last.toLowerCase();
  if (/\b(eat|ate|food|hungry|starv|lunch|dinner|snack)\b/.test(s)) {
    return pick(
      ["not yet", "just did", "starving", "same", "go eat", "i forgot too", "food first", "what's for dinner", "i need a snack", "fridge is empty"],
      rng,
    );
  }
  if (/\b(sleep|slept|nap|tired|bed|awake|up yet|gn)\b/.test(s)) {
    return pick(
      ["go sleep", "can't sleep", "same", "one more then i sleep", "i'm in bed", "should be in bed", "night crew", "rest", "half asleep", "alarm won"],
      rng,
    );
  }
  if (/\b(coffee|water|hydrat)\b/.test(s)) {
    return pick(["coffee first", "water first", "same", "hasn't hit", "hit too hard", "i'm on my second", "hydrate", "need that"], rng);
  }
  if (/\b(gm|morning|hey|yo|hi|sup|what's up|how you been)\b/.test(s)) {
    return pick(TALK_GREET, rng);
  }
  if (/\b(lol|lmao|funny)\b/.test(s)) {
    return pick(["lmao", "lol", "you're funny", "stop", "chat is a mess", "y'all wild", "i felt that", "ok ok"], rng);
  }
  if (/\?|anyone|you good|you still|what did i miss|or just me|same\?/.test(s)) {
    return pick(
      ["same", "not just you", "i'm here", "you good", "nothing much", "same as always", "i'm listening", "tell me", "or just me too", "we in the same boat", "mood", "real"],
      rng,
    );
  }
  if (rng() < 0.35) return pick(TALK_LINE, rng);
  return `${pick(TALK_BACK, rng)}${pick(TALK_BACK_END, rng)}`.replace(/\s+/g, " ").trim();
}
